spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:{EUREKA_PORT}/eureka